import { notFound } from 'next/navigation'
import Link from 'next/link'
import { auth } from '@/lib/auth'
import { getDb } from '@/lib/db'
import { prds, prdIssues, prdComments, issues, githubRepos, agents } from '@mobster/db'
import { eq, inArray } from 'drizzle-orm'
import { PrdViewer } from '@/components/prd-viewer'
import { PrdComments } from '@/components/prd-comments'
import { PrdStatusBadge } from '@/components/prd-status-badge'
import { StatusButton } from './status-button'
import { EmptyState } from '@/components/empty-state'
import { ArrowLeft, ExternalLink } from 'lucide-react'

interface PrdDetailPageProps {
  params: Promise<{ id: string }>
  searchParams: Promise<{}>
}

export default async function PrdDetailPage({ params }: PrdDetailPageProps) {
  const session = await auth()
  if (!session?.accessToken) {
    return (
      <EmptyState
        icon="🔗"
        title="Connect GitHub first"
        description="Sign in to view PRDs."
        action={{ label: 'Go to Settings', href: '/settings' }}
      />
    )
  }

  const { id } = await params
  const db = getDb()

  const prd = db.select().from(prds).where(eq(prds.id, id)).get()
  if (!prd) {
    notFound()
  }

  // Load linked issues
  const links = db.select().from(prdIssues).where(eq(prdIssues.prdId, id)).all()
  const linkedIssues =
    links.length > 0
      ? db
          .select()
          .from(issues)
          .where(inArray(issues.id, links.map((l) => l.issueId)))
          .all()
      : []

  // Enrich issues with repo name
  const enrichedIssues = linkedIssues.map((issue) => {
    const repo = db
      .select()
      .from(githubRepos)
      .where(eq(githubRepos.id, issue.repoId))
      .get()
    return {
      id: issue.id,
      number: issue.number,
      title: issue.title,
      state: issue.state,
      repoFullName: repo?.fullName ?? 'unknown',
      labels: parseLabels(issue.labels),
    }
  })

  // Load comments
  const comments = db.select().from(prdComments).where(eq(prdComments.prdId, id)).all()

  // Load agent info
  const agentName = prd.agentId
    ? db.select().from(agents).where(eq(agents.id, prd.agentId)).get()?.name ?? null
    : null

  return (
    <div className="space-y-6">
      {/* Back link */}
      <Link
        href="/prds"
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to PRDs
      </Link>

      {/* Header */}
      <div>
        <div className="flex items-start justify-between gap-4">
          <div className="space-y-2">
            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-bold">{prd.title}</h1>
              <PrdStatusBadge status={prd.status} />
              {prd.version > 1 && (
                <span className="text-sm text-muted-foreground">v{prd.version}</span>
              )}
            </div>
            <div className="flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
              {agentName && (
                <>
                  <span>Generated by {agentName}</span>
                  <span>·</span>
                </>
              )}
              {prd.agentModel && (
                <>
                  <span>{prd.agentModel}</span>
                  <span>·</span>
                </>
              )}
              <span>Created {new Date(prd.createdAt).toLocaleDateString()}</span>
              {prd.agentModel && (
                <>
                  <span>·</span>
                  <Link
                    href={`/runners/prd-${prd.id}-v${prd.version}`}
                    className="text-primary hover:underline"
                  >
                    View generation log →
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Linked issues */}
      {enrichedIssues.length > 0 && (
        <div className="rounded-lg border p-4 space-y-2">
          <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">
            Source Issues ({enrichedIssues.length})
          </h3>
          <div className="space-y-1">
            {enrichedIssues.map((issue) => (
              <Link
                key={issue.id}
                href={`/issues/${issue.id}`}
                className="flex items-center gap-2 text-sm hover:text-primary transition-colors py-1"
              >
                <span className="text-muted-foreground">#{issue.number}</span>
                <span>{issue.title}</span>
                <span className="text-xs text-muted-foreground">({issue.repoFullName})</span>
                <ExternalLink className="h-3 w-3 text-muted-foreground" />
              </Link>
            ))}
          </div>
        </div>
      )}

      {/* Status action buttons */}
      {prd.status === 'draft' && (
        <div className="flex items-center gap-2">
          <StatusButton prdId={prd.id} status="reviewed" label="Mark as Reviewed" />
          <StatusButton prdId={prd.id} status="approved" label="Skip to Approved" />
        </div>
      )}
      {prd.status === 'reviewed' && (
        <StatusButton prdId={prd.id} status="approved" label="Approve PRD" />
      )}
      {prd.status === 'approved' && (
        <div className="rounded-md border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700 dark:bg-green-900/30 dark:text-green-300">
          ✓ This PRD has been approved and is ready to be scheduled for execution (Phase 3).
        </div>
      )}
      {prd.status === 'failed' && (
        <div className="rounded-md border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-destructive">
          PRD generation failed. You may need to check your agent configuration or try again.
        </div>
      )}

      {/* PRD Content */}
      <PrdViewer content={prd.content} />

      {/* Comments */}
      <PrdComments
        prdId={prd.id}
        prdStatus={prd.status}
        initialComments={comments.map((c) => ({
          id: c.id,
          content: c.content,
          createdAt: c.createdAt,
        }))}
      />
    </div>
  )
}

// ─── Helpers ──────────────────────────────────────────

function parseLabels(labels: string | null): string[] {
  if (!labels) return []
  try {
    return JSON.parse(labels)
  } catch {
    return []
  }
}
